draw_on = "all"
stroke_size = 5
default_tool = "pen"
cursor.visible = true
clear_on_escape = false
remember_last_tool = true
default_color = "#E84046"
feedback_duration_ms = 500
default_fill_shapes = false
size_range = { min = 1, max = 100 }
stops = { size = [], opacity = [], roundness = [] }
steps = { size = 1, opacity = 0.01, roundness = 0.01 }

palette = [
  "#E84046",
  "#EF8F4F",
  "#EED14D",
  "#4DD54F",
  "#0483FA",
  "#7C58EA",
  "#EBEBEB",
  "#141414",
]

[tools]
line = { opacity = 1, roundness = 0.5 }
ellipse = { opacity = 1, filled = false }
eraser = { size = 10, cursor.visible = false }
triangle = { opacity = 1, roundness = 0.0, filled = false }
rectangle = { opacity = 1, roundness = 0.1, filled = false }
pen = { opacity = 1, roundness = 1, cursor.visible = false }
arrow = { opacity = 1, roundness = 0.25, cursor.visible = false }

[tools.text]
size = 16
opacity = 1
roundness = 0.1
steps.size = 0.5
background = false
font = { family = "sans-serif", weight = 400, style = "normal", features = {} }
size_range = { min = 8, max = 500 }
